import { LevelConfig, PlanetaryRegion } from '../types/game';

export const PLANETARY_REGIONS: Record<string, PlanetaryRegion> = {
  EARTH_ORBIT: {
    id: 'EARTH_ORBIT',
    nameTr: 'Dünya Yörüngesi',
    descriptionTr: 'Derin uzay boşluğunda başlayan ilk savunma hattı.',
    primaryColor: '#38bdf8',
    secondaryColor: '#0284c7',
    planetColor: '#0284c7',
    planetRing: false,
    bgGradient: ['#020617', '#030712'],
    ambientType: 'stars',
  },
  VOLCANIC: {
    id: 'VOLCANIC',
    nameTr: 'Volkanik Kuşak',
    descriptionTr: 'Erimiş akkor toz bulutları ve kor asteroit kuşağı.',
    primaryColor: '#f97316',
    secondaryColor: '#c2410c',
    planetColor: '#ea580c',
    planetRing: true,
    bgGradient: ['#0c0402', '#030712'],
    ambientType: 'lava',
  },
  ICE: {
    id: 'ICE',
    nameTr: 'Buzul Sistem',
    descriptionTr: 'Sıfırın altında donmuş kristal tozları ve derin karanlık.',
    primaryColor: '#67e8f9',
    secondaryColor: '#0891b2',
    planetColor: '#a5f3fc',
    planetRing: true,
    bgGradient: ['#020b14', '#030712'],
    ambientType: 'snow',
  },
  NEBULA: {
    id: 'NEBULA',
    nameTr: 'Nebula Bölgesi',
    descriptionTr: 'Mor ve pembe kozmik gaz bulutları arasındaki derin uzay.',
    primaryColor: '#c084fc',
    secondaryColor: '#7e22ce',
    planetColor: '#a855f7',
    planetRing: false,
    bgGradient: ['#0d0417', '#030712'],
    ambientType: 'gas',
  },
  DARK_GALAXY: {
    id: 'DARK_GALAXY',
    nameTr: 'Karanlık Galaksi',
    descriptionTr: 'Işığın zor ulaştığı derin uzay boşluğu ve pulsar yıldızları.',
    primaryColor: '#818cf8',
    secondaryColor: '#4338ca',
    planetColor: '#312e81',
    planetRing: true,
    bgGradient: ['#020208', '#000000'],
    ambientType: 'dark',
  },
  FINAL_PLANET: {
    id: 'FINAL_PLANET',
    nameTr: 'Son Bölge & Kozmik Merkez',
    descriptionTr: 'Kozmik fırtınanın kaynağı olan kadim enerji merkezi.',
    primaryColor: '#f43f5e',
    secondaryColor: '#e11d48',
    planetColor: '#e11d48',
    planetRing: true,
    bgGradient: ['#0f0206', '#020002'],
    ambientType: 'core',
  },
};

export const LEVELS: LevelConfig[] = [
  // REGION 1: EARTH ORBIT (Levels 1-4)
  {
    id: 1,
    name: 'İlk Adım',
    regionId: 'EARTH_ORBIT',
    durationSeconds: 120,
    objective: {
      type: 'DESTROY_ASTEROIDS',
      target: 30,
      labelTr: '30 göktaşını temizle ve gelen düşman liderini yok et!',
    },
    asteroidRate: 1.1,
    asteroidSpeedMultiplier: 0.85,
    enemySpawnRate: 0.24,
    allowedAsteroids: ['SMALL', 'MEDIUM'],
    allowedEnemies: ['SCOUT'],
    hasBoss: true,
    bossType: 'RIVAL_FIGHTER',
    bossName: 'Gölge Keşif Kruvazörü',
    briefing: [
      {
        speaker: 'HQ_COMMAND',
        speakerNameTr: 'Merkez Komuta',
        avatar: '📡',
        textTr: 'Kaptan Nova, radarımızda yoğun asteroit fırtınası tespit edildi. Alanı temizle ve arkasındaki düşman keşif liderini etkisiz hale getir!',
      },
      {
        speaker: 'NOVA_PILOT',
        speakerNameTr: 'Kaptan Nova',
        avatar: '🚀',
        textTr: 'Anlaşıldı Merkez! Nova gemisi hazır. Asteroitleri geçip rakip lideri indireceğim!',
      },
    ],
  },
  {
    id: 2,
    name: 'Taş Yağmuru',
    regionId: 'EARTH_ORBIT',
    durationSeconds: 180,
    objective: {
      type: 'DESTROY_ASTEROIDS',
      target: 75,
      labelTr: '75 göktaşını yok et ve Korsan Savaş Gemisini yen!',
    },
    asteroidRate: 1.6,
    asteroidSpeedMultiplier: 0.95,
    enemySpawnRate: 0.55,
    allowedAsteroids: ['SMALL', 'MEDIUM', 'LARGE', 'ARMOR'],
    allowedEnemies: ['SCOUT'],
    hasBoss: true,
    bossType: 'RIVAL_CRUISER',
    bossName: 'Korsan Savaş Gemisi',
    briefing: [
      {
        speaker: 'HQ_COMMAND',
        speakerNameTr: 'Merkez Komuta',
        avatar: '📡',
        textTr: 'Devasa bir Taş Yağmuru fırtınası başladı! 75 göktaşını parçala ve korsan kruvazörünü durdur!',
      },
    ],
  },
  {
    id: 3,
    name: 'Mor Bulut',
    regionId: 'EARTH_ORBIT',
    durationSeconds: 190,
    objective: {
      type: 'COLLECT_CRYSTALS',
      target: 18,
      labelTr: '18 Kristal topla ve Plazma Akıncısını yok et!',
    },
    asteroidRate: 1.7,
    asteroidSpeedMultiplier: 1.0,
    enemySpawnRate: 0.6,
    allowedAsteroids: ['SMALL', 'MEDIUM', 'CRYSTAL', 'LARGE'],
    allowedEnemies: ['SCOUT'],
    hasBoss: true,
    bossType: 'RIVAL_FIGHTER',
    bossName: 'Plazma Akıncısı',
    briefing: [
      {
        speaker: 'NOVA_PILOT',
        speakerNameTr: 'Kaptan Nova',
        avatar: '🚀',
        textTr: 'Kristalleri toplayıp silahımı güçlendireceğim. Düşman akıncısı yaklaşıyor!',
      },
    ],
  },
  {
    id: 4,
    name: 'Kristal Alan',
    regionId: 'EARTH_ORBIT',
    durationSeconds: 200,
    objective: {
      type: 'SURVIVE_TIME',
      target: 110,
      labelTr: '110 sn hayatta kal ve Siber Fırkateyni yok et!',
    },
    asteroidRate: 1.9,
    asteroidSpeedMultiplier: 1.05,
    enemySpawnRate: 0.65,
    allowedAsteroids: ['SMALL', 'MEDIUM', 'LARGE', 'CRYSTAL', 'EXPLOSIVE'],
    allowedEnemies: ['SCOUT', 'DRONE'],
    hasBoss: true,
    bossType: 'RIVAL_CRUISER',
    bossName: 'Siber Muhafız Fırkateyni',
    briefing: [
      {
        speaker: 'HQ_COMMAND',
        speakerNameTr: 'Merkez Komuta',
        avatar: '📡',
        textTr: 'Dünya yörüngesinden çıkış noktasında güçlü bir Siber Fırkateyn bekliyor!',
      },
    ],
  },

  // REGION 2: VOLCANIC (Levels 5-8)
  {
    id: 5,
    name: 'Volkan Geçidi',
    regionId: 'VOLCANIC',
    durationSeconds: 210,
    objective: {
      type: 'DEFEAT_BOSS',
      target: 1,
      labelTr: 'Asteroit Muhafız Gemisini yok et!',
    },
    asteroidRate: 1.5,
    asteroidSpeedMultiplier: 1.05,
    enemySpawnRate: 0.6,
    allowedAsteroids: ['SMALL', 'MEDIUM', 'ARMOR', 'LARGE'],
    allowedEnemies: ['SCOUT'],
    hasBoss: true,
    bossType: 'ASTEROID_GUARDIAN',
    bossName: 'Asteroit Muhafızı Zırhlısı',
    briefing: [
      {
        speaker: 'HQ_COMMAND',
        speakerNameTr: 'Merkez Komuta',
        avatar: '⚠️',
        textTr: 'DİKKAT! Volkanik geçitte devasa bir lav zırhlısı lider tespit edildi: Asteroit Muhafızı!',
      },
      {
        speaker: 'NOVA_PILOT',
        speakerNameTr: 'Kaptan Nova',
        avatar: '🚀',
        textTr: 'Ağır topları var. Zayıf noktalarını hedef alarak geçiş çizgisini açacağım!',
      },
    ],
  },
  {
    id: 6,
    name: 'Donmuş Yörünge',
    regionId: 'VOLCANIC',
    durationSeconds: 200,
    objective: {
      type: 'DESTROY_ASTEROIDS',
      target: 85,
      labelTr: '85 göktaşını temizle ve Rakip Taarruz Gemisini yok et!',
    },
    asteroidRate: 2.0,
    asteroidSpeedMultiplier: 1.1,
    enemySpawnRate: 0.65,
    allowedAsteroids: ['SMALL', 'MEDIUM', 'LARGE', 'EXPLOSIVE', 'ARMOR'],
    allowedEnemies: ['SCOUT', 'DRONE'],
    hasBoss: true,
    bossType: 'RIVAL_BATTLESHIP',
    bossName: 'Ağır Zırhlı Taarruz Gemisi',
    briefing: [
      {
        speaker: 'HQ_COMMAND',
        speakerNameTr: 'Merkez Komuta',
        avatar: '📡',
        textTr: 'Patlayıcı asteroitler yoğun. Arkadaki Ağır Taarruz Gemisine karşı dikkatli ol!',
      },
    ],
  },
  {
    id: 7,
    name: 'Asteroit Kuşağı',
    regionId: 'VOLCANIC',
    durationSeconds: 210,
    objective: {
      type: 'DESTROY_ASTEROIDS',
      target: 95,
      labelTr: '95 göktaşını yok et ve Gece Kartalı Amiral Gemisini yen!',
    },
    asteroidRate: 2.2,
    asteroidSpeedMultiplier: 1.15,
    enemySpawnRate: 0.7,
    allowedAsteroids: ['SMALL', 'MEDIUM', 'LARGE', 'ARMOR'],
    allowedEnemies: ['SCOUT', 'DRONE'],
    hasBoss: true,
    bossType: 'RIVAL_FLAGSHIP',
    bossName: 'Gece Kartalı Amiral Gemisi',
    briefing: [
      {
        speaker: 'NOVA_PILOT',
        speakerNameTr: 'Kaptan Nova',
        avatar: '🚀',
        textTr: 'Düşman amirali kuşağı kapatmış. Onu yenip hiper geçit çizgisine ulaşacağım!',
      },
    ],
  },
  {
    id: 8,
    name: 'Kararma',
    regionId: 'VOLCANIC',
    durationSeconds: 215,
    objective: {
      type: 'SURVIVE_TIME',
      target: 120,
      labelTr: '120 sn diren ve Volkanik Savaş Kruvazörünü yok et!',
    },
    asteroidRate: 2.3,
    asteroidSpeedMultiplier: 1.2,
    enemySpawnRate: 0.75,
    allowedAsteroids: ['SMALL', 'MEDIUM', 'LARGE', 'CRYSTAL', 'EXPLOSIVE'],
    allowedEnemies: ['SCOUT', 'DRONE'],
    hasBoss: true,
    bossType: 'RIVAL_CRUISER',
    bossName: 'Volkanik Savaş Kruvazörü',
    briefing: [
      {
        speaker: 'HQ_COMMAND',
        speakerNameTr: 'Merkez Komuta',
        avatar: '📡',
        textTr: 'Görüş düşük. Radar sinyallerini izle ve lider gemiyi yok et!',
      },
    ],
  },

  // REGION 3: ICE SYSTEM (Levels 9-12)
  {
    id: 9,
    name: 'Eski İstasyon',
    regionId: 'ICE',
    durationSeconds: 210,
    objective: {
      type: 'COLLECT_CRYSTALS',
      target: 20,
      labelTr: '20 Buzul Kristali topla ve Hayalet Gemiyi yen!',
    },
    asteroidRate: 2.2,
    asteroidSpeedMultiplier: 1.15,
    enemySpawnRate: 0.75,
    allowedAsteroids: ['SMALL', 'MEDIUM', 'CRYSTAL', 'ARMOR', 'LARGE'],
    allowedEnemies: ['SCOUT', 'DRONE'],
    hasBoss: true,
    bossType: 'RIVAL_FIGHTER',
    bossName: 'Buzul Hayalet Gemi',
    briefing: [
      {
        speaker: 'NOVA_PILOT',
        speakerNameTr: 'Kaptan Nova',
        avatar: '🚀',
        textTr: 'Terk edilmiş istasyonun çevresini koruyan hayalet savaş uçağı tespit edildi.',
      },
    ],
  },
  {
    id: 10,
    name: 'Galaksi Kapısı',
    regionId: 'ICE',
    durationSeconds: 230,
    objective: {
      type: 'DEFEAT_BOSS',
      target: 1,
      labelTr: 'Yıkıcı Savaş Gemisini yok et!',
    },
    asteroidRate: 1.8,
    asteroidSpeedMultiplier: 1.2,
    enemySpawnRate: 0.7,
    allowedAsteroids: ['SMALL', 'MEDIUM', 'CRYSTAL', 'LARGE'],
    allowedEnemies: ['SCOUT', 'DRONE'],
    hasBoss: true,
    bossType: 'SPACE_DESTROYER',
    bossName: 'Yıkıcı Savaş Kruvazörü',
    briefing: [
      {
        speaker: 'HQ_COMMAND',
        speakerNameTr: 'Merkez Komuta',
        avatar: '🚨',
        textTr: 'Galaksi Kapısını yabancı bir süper kruvazör kapatmış! Bu Yıkıcı Savaş Gemisini yok etmeden geçit açılamaz.',
      },
      {
        speaker: 'NOVA_PILOT',
        speakerNameTr: 'Kaptan Nova',
        avatar: '🚀',
        textTr: 'Kalkanlar hazır! Kapıyı açıp geçiş çizgisinden atlayacağım!',
      },
    ],
  },
  {
    id: 11,
    name: 'Plazma Fırtınası',
    regionId: 'ICE',
    durationSeconds: 220,
    objective: {
      type: 'DESTROY_ASTEROIDS',
      target: 110,
      labelTr: '110 göktaşını temizle ve Plazma Amiral Gemisini yen!',
    },
    asteroidRate: 2.5,
    asteroidSpeedMultiplier: 1.25,
    enemySpawnRate: 0.8,
    allowedAsteroids: ['SMALL', 'MEDIUM', 'LARGE', 'EXPLOSIVE', 'ARMOR'],
    allowedEnemies: ['SCOUT', 'DRONE', 'HEAVY'],
    hasBoss: true,
    bossType: 'RIVAL_FLAGSHIP',
    bossName: 'Plazma Amiral Gemisi',
    briefing: [
      {
        speaker: 'NOVA_PILOT',
        speakerNameTr: 'Kaptan Nova',
        avatar: '🚀',
        textTr: 'Plazma yüklü fırtınanın ortasında düşman amirali bekliyor!',
      },
    ],
  },
  {
    id: 12,
    name: 'Dev Gezegen',
    regionId: 'ICE',
    durationSeconds: 230,
    objective: {
      type: 'SURVIVE_TIME',
      target: 130,
      labelTr: '130 sn hayatta kal ve Göktaşı Delici Kruvazörü yok et!',
    },
    asteroidRate: 2.6,
    asteroidSpeedMultiplier: 1.25,
    enemySpawnRate: 0.85,
    allowedAsteroids: ['SMALL', 'MEDIUM', 'LARGE', 'ARMOR', 'CRYSTAL'],
    allowedEnemies: ['SCOUT', 'DRONE', 'HEAVY'],
    hasBoss: true,
    bossType: 'RIVAL_BATTLESHIP',
    bossName: 'Göktaşı Delici Savaş Gemisi',
    briefing: [
      {
        speaker: 'HQ_COMMAND',
        speakerNameTr: 'Merkez Komuta',
        avatar: '📡',
        textTr: 'Devasa yerçekimi alanında düşman zırhlısı sana doğru ilerliyor!',
      },
    ],
  },

  // REGION 4: NEBULA (Levels 13-16)
  {
    id: 13,
    name: 'Derin Uzay',
    regionId: 'NEBULA',
    durationSeconds: 225,
    objective: {
      type: 'DESTROY_ASTEROIDS',
      target: 120,
      labelTr: '120 göktaşını yok et ve Derin Uzay Avcısını yen!',
    },
    asteroidRate: 2.7,
    asteroidSpeedMultiplier: 1.3,
    enemySpawnRate: 0.85,
    allowedAsteroids: ['SMALL', 'MEDIUM', 'LARGE', 'CRYSTAL', 'ARMOR'],
    allowedEnemies: ['SCOUT', 'DRONE', 'HEAVY'],
    hasBoss: true,
    bossType: 'RIVAL_FIGHTER',
    bossName: 'Derin Uzay Avcısı',
    briefing: [
      {
        speaker: 'NOVA_PILOT',
        speakerNameTr: 'Kaptan Nova',
        avatar: '🚀',
        textTr: 'Nebula gazları arasında gizlenen çevik avcı gemiyi radarda yakaladım!',
      },
    ],
  },
  {
    id: 14,
    name: 'Yabancı Bölge',
    regionId: 'NEBULA',
    durationSeconds: 230,
    objective: {
      type: 'COLLECT_CRYSTALS',
      target: 24,
      labelTr: '24 Çekirdek topla ve İstilacı Filo Liderini yok et!',
    },
    asteroidRate: 2.8,
    asteroidSpeedMultiplier: 1.3,
    enemySpawnRate: 0.9,
    allowedAsteroids: ['SMALL', 'MEDIUM', 'CRYSTAL', 'ARMOR', 'LARGE'],
    allowedEnemies: ['SCOUT', 'DRONE', 'HEAVY', 'ELITE'],
    hasBoss: true,
    bossType: 'RIVAL_CRUISER',
    bossName: 'İstilacı Filo Lideri',
    briefing: [
      {
        speaker: 'HQ_COMMAND',
        speakerNameTr: 'Merkez Komuta',
        avatar: '📡',
        textTr: 'Kadim çekirdekleri topla ve istilacı lideri yenerek geçiş hattını aç!',
      },
    ],
  },
  {
    id: 15,
    name: 'Kaybolmuş Uydu',
    regionId: 'NEBULA',
    durationSeconds: 240,
    objective: {
      type: 'DEFEAT_BOSS',
      target: 1,
      labelTr: 'Nebula Canavarı Savaş Makinesini yok et!',
    },
    asteroidRate: 2.0,
    asteroidSpeedMultiplier: 1.3,
    enemySpawnRate: 0.75,
    allowedAsteroids: ['SMALL', 'MEDIUM', 'CRYSTAL', 'LARGE'],
    allowedEnemies: ['SCOUT', 'DRONE'],
    hasBoss: true,
    bossType: 'NEBULA_BEAST',
    bossName: 'Nebula Canavarı Savaş Gemisi',
    briefing: [
      {
        speaker: 'HQ_COMMAND',
        speakerNameTr: 'Merkez Komuta',
        avatar: '⚠️',
        textTr: 'Nebula kalbinde devasa biyo-mekanik bir savaş makinesi uyandı!',
      },
      {
        speaker: 'NOVA_PILOT',
        speakerNameTr: 'Kaptan Nova',
        avatar: '🚀',
        textTr: 'Tüm silah sistemlerini tam güce alıyorum. Bu makineyi durdurup Karanlık Galaksiye geçeceğim!',
      },
    ],
  },
  {
    id: 16,
    name: 'Nebula',
    regionId: 'NEBULA',
    durationSeconds: 235,
    objective: {
      type: 'SURVIVE_TIME',
      target: 140,
      labelTr: '140 sn diren ve Yıldız Kıran Savaş Gemisini yok et!',
    },
    asteroidRate: 2.9,
    asteroidSpeedMultiplier: 1.35,
    enemySpawnRate: 0.9,
    allowedAsteroids: ['SMALL', 'MEDIUM', 'LARGE', 'EXPLOSIVE', 'CRYSTAL', 'ARMOR'],
    allowedEnemies: ['SCOUT', 'DRONE', 'HEAVY', 'ELITE'],
    hasBoss: true,
    bossType: 'RIVAL_BATTLESHIP',
    bossName: 'Yıldız Kıran Savaş Gemisi',
    briefing: [
      {
        speaker: 'HQ_COMMAND',
        speakerNameTr: 'Merkez Komuta',
        avatar: '📡',
        textTr: 'Nebula çıkış kapısında devasa Yıldız Kıran bekliyor!',
      },
    ],
  },

  // REGION 5: DARK GALAXY (Levels 17-19)
  {
    id: 17,
    name: 'Karanlık Alan',
    regionId: 'DARK_GALAXY',
    durationSeconds: 240,
    objective: {
      type: 'DESTROY_ASTEROIDS',
      target: 130,
      labelTr: '130 göktaşını temizle ve Karanlık Amiral Gemisini yen!',
    },
    asteroidRate: 3.0,
    asteroidSpeedMultiplier: 1.4,
    enemySpawnRate: 0.95,
    allowedAsteroids: ['SMALL', 'MEDIUM', 'LARGE', 'ARMOR', 'EXPLOSIVE'],
    allowedEnemies: ['SCOUT', 'HEAVY', 'ELITE'],
    hasBoss: true,
    bossType: 'RIVAL_FLAGSHIP',
    bossName: 'Karanlık Galaksi Amiral Gemisi',
    briefing: [
      {
        speaker: 'NOVA_PILOT',
        speakerNameTr: 'Kaptan Nova',
        avatar: '🚀',
        textTr: 'Karanlık Galaksinin baş komutanı karşımda. Kalkanlarını parçalayacağım!',
      },
    ],
  },
  {
    id: 18,
    name: 'Son Geçit',
    regionId: 'DARK_GALAXY',
    durationSeconds: 245,
    objective: {
      type: 'DESTROY_ASTEROIDS',
      target: 150,
      labelTr: '150 göktaşını yok et ve Savunma Titanını imha et!',
    },
    asteroidRate: 3.2,
    asteroidSpeedMultiplier: 1.45,
    enemySpawnRate: 1.0,
    allowedAsteroids: ['SMALL', 'MEDIUM', 'LARGE', 'EXPLOSIVE', 'ARMOR'],
    allowedEnemies: ['SCOUT', 'DRONE', 'HEAVY', 'ELITE'],
    hasBoss: true,
    bossType: 'RIVAL_BATTLESHIP',
    bossName: 'Son Savunma Titan Gemisi',
    briefing: [
      {
        speaker: 'HQ_COMMAND',
        speakerNameTr: 'Merkez Komuta',
        avatar: '📡',
        textTr: 'Kozmik merkezin son kapısını tutan Titan gemisini temizle!',
      },
    ],
  },
  {
    id: 19,
    name: 'Fırtınanın Merkezi',
    regionId: 'DARK_GALAXY',
    durationSeconds: 250,
    objective: {
      type: 'SURVIVE_TIME',
      target: 150,
      labelTr: '150 sn diren ve Fırtına Süvarisi Titan Gemisini yen!',
    },
    asteroidRate: 3.4,
    asteroidSpeedMultiplier: 1.5,
    enemySpawnRate: 1.05,
    allowedAsteroids: ['SMALL', 'MEDIUM', 'LARGE', 'CRYSTAL', 'EXPLOSIVE', 'ARMOR'],
    allowedEnemies: ['SCOUT', 'DRONE', 'HEAVY', 'ELITE'],
    hasBoss: true,
    bossType: 'RIVAL_FLAGSHIP',
    bossName: 'Fırtına Süvarisi Titan Gemi',
    briefing: [
      {
        speaker: 'NOVA_PILOT',
        speakerNameTr: 'Kaptan Nova',
        avatar: '🚀',
        textTr: 'Son aşamadayız! Titan gemisini yenip nihai merkeze geçeceğim!',
      },
    ],
  },

  // REGION 6: FINAL PLANET (Level 20)
  {
    id: 20,
    name: 'Son Gezegen',
    regionId: 'FINAL_PLANET',
    durationSeconds: 280,
    objective: {
      type: 'DEFEAT_BOSS',
      target: 1,
      labelTr: 'Kozmik Fırtına Çekirdeği & Amiral Gemisini yok et!',
    },
    asteroidRate: 2.4,
    asteroidSpeedMultiplier: 1.35,
    enemySpawnRate: 0.85,
    allowedAsteroids: ['SMALL', 'MEDIUM', 'CRYSTAL', 'EXPLOSIVE', 'LARGE', 'ARMOR'],
    allowedEnemies: ['SCOUT', 'ELITE', 'DRONE'],
    hasBoss: true,
    bossType: 'COSMIC_CORE',
    bossName: 'Kozmik Fırtına Çekirdeği',
    briefing: [
      {
        speaker: 'HQ_COMMAND',
        speakerNameTr: 'Merkez Komuta',
        avatar: '🔴',
        textTr: 'KAPTAN NOVA! İşte fırtınanın ana kontrol merkezi! Tüm galaksinin kaderi senin ellerinde!',
      },
      {
        speaker: 'ANCIENT_AI',
        speakerNameTr: 'Kadim Muhafız',
        avatar: '👁️',
        textTr: 'Nova gemisi burada son bulacak...',
      },
      {
        speaker: 'NOVA_PILOT',
        speakerNameTr: 'Kaptan Nova',
        avatar: '🚀',
        textTr: 'Galaksiyi kurtaracağız! Tüm silah sistemleri maksimum aşırı yüklemede!',
      },
    ],
    debriefing: [
      {
        speaker: 'NOVA_PILOT',
        speakerNameTr: 'Kaptan Nova',
        avatar: '🚀',
        textTr: 'Çekirdek imha edildi! Fırtına dağılıyor... Galaksi nihayet güvende!',
      },
    ],
  },
];
